apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    foo: bar
spec:
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: node
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          foo: bar
  containers:
    - image: 192.168.178.15:5000/img_proc:latest
      name: img-processor

---
apiVersion: v1
kind: Service
metadata:
  name: image-processor-service
spec:
  selector:
    app: img-processor
  ports:
    - protocol: "TCP"
      port: 6000
      targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-processor-server
spec:
  selector:
    matchLabels:
      app: img-processor
  replicas: 3
  template:
    metadata:
      labels:
        app: img-processor
    spec:
      containers:
        - name: img-processor
          image: 192.168.178.15:5000/img_proc:latest
          ports:
            - containerPort: 8000
